= Mule Cassandra Connector - Support Information
:imagesdir: _images
:toc:

= Apache Cassandra Information

== Documentation Links

. link:https://cassandra.apache.org/doc/latest/[Apache Cassandra Documentation]
. link:https://docs.datastax.com/en/developer/java-driver/3.1/manual/[Datastax Java Driver for Apache Cassandra]
. link:https://cassandra.apache.org/doc/latest/getting_started/installing.html[Installing Cassandra]
. link:https://cassandra.apache.org/doc/old/CQL-3.0.html[CQL Documentation]

== Documentation used by the conn dev to build it.

See: <<Documentation Links>>

= Contacts names

== Developers

=== Development Team Leader
* mailto:martin.paoloni@mulesoft.com[Martin Paoloni]
* slack-user: @martin.paoloni

=== Development Team
* Main developer:
** mailto:ezequiel.sandoval@mulesoft.com[Ezequiel Sandoval]
** slack-user: @ezequiel.sandoval

== Engineering Manager

* mailto:marcos.nunezcortes@mulesoft.com[Marcos Nuñez Cortes]
* slack-user: @marcos.nunezcortes

== SME on the platform

//Subject matter expert contact

== Slack Channels

Connectors support channel
https://mulesoft.slack.com/archives/connectors

= Technical details

== Sandbox

Apache Cassandra is a open source software and can be installed following the instructions http://cassandra.apache.org/download/[Cassandra Download]

After finishing the installation find the **cassandra.yaml** config file and change the value of the authenticator from **AllowAllAuthenticator** to **PasswordAuthenticator**(if the authenticator is not changed one can log in without specifying the username and the password for the database).

After starting the cassandra service, you can connect to the database that will be running at port 9042 by default.

The default credentials are cassandra/cassandra but also other admin accounts can be created by executing different queries explained http://docs.datastax.com/en/cql/3.1/cql/cql_reference/create_user_r.html[here]

=== Tools

There are multiple tools that allow users to interact with Cassandra Databases.

The first of all is the CQLSH terminal which comes bundled within the Cassandra installation.

A much better tool would be DataStax Studio which is an interactive developer tool and can be downloaded https://www.datastax.com/products/datastax-studio-and-development-tools[here]

Another tool that offers a graphic UI to interact with Cassandra would be DBeaver which can be downloaded http://dbeaver.jkiss.org/[here]

== Authentication methods

=== Available for the platform

Authentication is pluggable in Cassandra and is configured using the authenticator setting in **cassandra.yaml**.

Cassandra ships with two options included in the default distribution:

. AllowAllAuthenticator

. PasswordAuthenticator

For more details regarding Cassandra authentication and authorization methods check this http://cassandra.apache.org/doc/latest/operating/security.html#authentication[link]

=== Currently available in the connector

The connector supports Basic Authentication.

If Cassandra is configured to use the AllowAllAuthenticator the user can leave the values for the username and password empty in the Connection Strategy.

Otherwise, if Cassandra is configured with the PasswordAuthenticator, the username and password must be specified.

The other connection parameters are **host**(default: localhost), **port**(default: 9042) and **keyspace**(default: empty). This is the default keyspace if not provided at operation level.

There is also an Advanced Configuration section where one can specify:

. Cluster Name - Cassandra cluster name.
. Protocol Version - Version of the native protocol supported by the driver.(V1("1.2.0"), V2("2.0.0"), V3("2.1.0"), V4("2.2.0"))
. Max Schema Agreement Wait Seconds - The maximum time to wait for schema agreement before returning from a DDL query.
. Compression - The compression to use for the transport.(Values: NONE, SNAPPY, LZ4)
. SSL - Enables the use of SSL for the cluster.

== Implementation details

The connector was implemented using the Datastax Java Driver for Apache Cassandra and exposes multiple operations that are described in the javadoc[LINK].
Some of these processors accept some custom POJOs as input parameters(needed for the datasense functionality).

=== Tips and tricks

**Important Note**: The operations of the connector that require a Data Type support only primitive data types(All of the types specified http://docs.datastax.com/en/cql/3.1/cql/cql_reference/cql_data_types_c.html[here] except **list**, **map**, **set** and **tuple**).

In order to create a table with columns having one of those types, or adding a new column of one of the complex types to an existing table, an user can use the **Execute CQL operation**.

Given the fact that our mapping of the Data Type for primitives is using uppercase, the user must either specify the type in uppercase or use a transformer to map th type to uppercase:
[source]
{
 "columns": payload.columns map {
  name: $.name,
  primaryKey: $.primaryKey,
  type: upper $.type
 }

== Troubleshooting
=== Logging level

*package to log*

. [small]#org.mule.modules.cassandradb#

=== Communication debug

By setting logging level to "DEBUG" for [small]#org.mule.modules.cassandradb# every operation executed will be logged.

== Entry points

On the connector class CassandraOperations.java you will find the operations you’d like to debug. The name of the operation is defined by friendlyName decorator parameter, or if the parameter is absent, by the name of the method,

== Logging from platform side

Go to the location of the Apache Cassandra installation folder and in the LOGS directory there will be a system.log file

= Escalation processes

=== JIRA Projects / Components

* Jira Project Key: https://www.mulesoft.org/jira/projects/CASS/:[CASS]

= General links

== Release notes

* [Cassandra Connector Release Notes]

== Documentation for the connector

* Cassandra User Manual
* Cassandra ApiDocs

== Github project

* https://github.com/mulesoft/cassandra-connector

== Example github project

* https://github.com/mulesoft/cassandra-connector/tree/develop/demo:[GitHub demo folder]
